### PR TITLE
Fix issue1 and update README to explain train test data splitting

### PR DESCRIPTION
**Pull request by Counterfly**
maybe the .rar file changed how the filenames but either way i think this is your intention

### CODE REVIEW

**Comment by harvitronix** [comment]
Hi @Counterfly, thanks for the PR! Can you explain why  you're removing the `v_` and `_`?  What's the purpose there?

**Comment by Counterfly** [comment]
Theres no real reason.  I thought it just looked nicer because every file will be prefixed with 'v_' then the information you care about.  I can modify the code to keep those if you would like.

**Comment by harvitronix** [comment]
Okay I think I understand now. The train/test files that you added are different from the official versions. My bad! I am merging a PR now with the official files, which are in a slightly different format to yours.

I'll merge mine now and take a look. If you still think those changes work, I'm happy to merge.

**Comment by Counterfly** [comment]
just FYI, your txt files (trainlistX testlistX) are still prefixed with the directory.
This rar file is flat.  each video is under the same folder thus these list.txt files will have incorrect paths.
You either have to:
  1) remove the directory prefix
  2) add the directory prefix to each file after unrar-ing the compressed data file

**Comment by harvitronix** [comment]
Right, that's why when moving the files, I use the filename extracted from the path, not the whole path.

**Pull request closed without merging**
